/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.dinnermenu2;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ajswe
 */
public class ChooseMeal extends javax.swing.JFrame {
    private Component popup;

    /**
     * Creates new form ChooseMeal
     * @param menu
     * @param settings
     */
    public ChooseMeal(ArrayList<Meal> menu, Settings settings, String menu_file_name, String parsing_check) {
        //Set up window
        setDefaultCloseOperation(ChooseMeal.EXIT_ON_CLOSE);
        try {
            Image image = new ImageIcon("icon.png").getImage();
            this.setIconImage(image);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(popup, "Application icon not found!");
        }
        initComponents();
        this.setTitle("Dinner Menu");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        
        //Initialize variables
        this.menu = menu;
        this.menu_file_name = menu_file_name;
        this.parsing_check = parsing_check;
        menu_list.removeAllItems();
        for(int i = 0; i < menu.size(); i++)
        {
            menu_list.addItem(menu.get(i).name);
        }
        this.settings = settings;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select_meal_label = new javax.swing.JLabel();
        menu_list = new javax.swing.JComboBox();
        edit_meal_button = new javax.swing.JButton();
        go_back_button = new javax.swing.JButton();
        delete_meal_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        select_meal_label.setText("Select a Meal to Edit");

        menu_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        edit_meal_button.setText("Edit Meal");
        edit_meal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_meal_buttonActionPerformed(evt);
            }
        });

        go_back_button.setText("Go Back");
        go_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_back_buttonActionPerformed(evt);
            }
        });

        delete_meal_button.setText("Delete Meal");
        delete_meal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_meal_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select_meal_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edit_meal_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete_meal_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menu_list, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go_back_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_meal_label)
                    .addComponent(menu_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_meal_button)
                    .addComponent(go_back_button)
                    .addComponent(delete_meal_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void go_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_back_buttonActionPerformed
        dispose();
        InitialMenu next_window;
        try {
            next_window = new InitialMenu();
            next_window.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ChooseMeal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_go_back_buttonActionPerformed

    private void edit_meal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_meal_buttonActionPerformed
        dispose();
        String prepop_meal = (String)menu_list.getSelectedItem();
        AddMeal next_window = new AddMeal(menu,prepop_meal,settings, menu_file_name, parsing_check);
        next_window.setVisible(true);
    }//GEN-LAST:event_edit_meal_buttonActionPerformed

    private void delete_meal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_meal_buttonActionPerformed
        String to_remove = "";
        for (int i = 0; i < menu.size(); i++) {
            if (menu.get(i).name.equals((String) menu_list.getSelectedItem())) {
                to_remove = menu.get(i).name;
                menu.remove(i);
            }
        }
        
        //Create a dummy AddMeal object to use write_to_db function
        AddMeal dummy = new AddMeal(menu,"",settings, menu_file_name, parsing_check);
        try {
            dummy.write_to_db();
            JOptionPane.showMessageDialog(popup, to_remove + " deleted!");
            dispose();
            if (menu.isEmpty()) {
                JOptionPane.showMessageDialog(popup, "All meals deleted, returning to main menu!");
                InitialMenu next_window;
                try {
                    next_window = new InitialMenu();
                    next_window.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ChooseMeal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                ChooseMeal newFrame = new ChooseMeal(menu,settings, menu_file_name, parsing_check);
                newFrame.setVisible(true);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseMeal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delete_meal_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_meal_button;
    private javax.swing.JButton edit_meal_button;
    private javax.swing.JButton go_back_button;
    private javax.swing.JComboBox menu_list;
    private javax.swing.JLabel select_meal_label;
    // End of variables declaration//GEN-END:variables
    public ArrayList<Meal> menu;
    private final Settings settings;
    private final String menu_file_name;
    private final String parsing_check;
}
