/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.dinnermenu2;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ajswe
 */
public class CurrentIngredients extends javax.swing.JFrame {

    private static Component popup;
    /**
     * Creates new form CurrentIngredients
     * @param menu
     * @param settings
     */
    public CurrentIngredients(ArrayList<Meal> menu, Settings settings) {
        setDefaultCloseOperation(CurrentIngredients.EXIT_ON_CLOSE);
        try {
            Image image = new ImageIcon("icon.png").getImage();
            this.setIconImage(image);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(popup, "Application icon not found!");
        }
        initComponents();
        this.setTitle("Dinner Menu");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        
        this.settings = settings;
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        current_ingredients_text = new javax.swing.JLabel();
        yes_ingredients = new javax.swing.JButton();
        no_ingredients = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        current_ingredients_text.setText("Do you have any ingredients you want to use up this week?");

        yes_ingredients.setText("Yes");
        yes_ingredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_ingredientsActionPerformed(evt);
            }
        });

        no_ingredients.setText("No");
        no_ingredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_ingredientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(current_ingredients_text)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(yes_ingredients)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_ingredients)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(current_ingredients_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes_ingredients)
                    .addComponent(no_ingredients))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yes_ingredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_ingredientsActionPerformed
        dispose();
        EnterIngredients next_window;
        next_window = new EnterIngredients(menu,settings);
        next_window.setVisible(true);
    }//GEN-LAST:event_yes_ingredientsActionPerformed

    private void no_ingredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_ingredientsActionPerformed
        dispose();
        MenuConfig next_window;
        next_window = new MenuConfig(menu,settings,null);
        next_window.setVisible(true);
    }//GEN-LAST:event_no_ingredientsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel current_ingredients_text;
    private javax.swing.JButton no_ingredients;
    private javax.swing.JButton yes_ingredients;
    // End of variables declaration//GEN-END:variables
    private final Settings settings;
    private ArrayList<Meal> menu;
}
